// Copies the built SPA (./dist) into the .NET host's wwwroot for single-deploy.
// Run after `vite build` (the npm "deploy" script does both). Idempotent: wwwroot
// is wiped and repopulated each run so stale hashed assets don't accumulate.
import { rm, mkdir, cp, access, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(here, '..', 'dist');
const wwwroot = resolve(here, '..', '..', 'drydock.backend-services', 'Drydock.Api', 'wwwroot');

try {
  await access(distDir);
} catch {
  console.error(`[deploy] dist not found at ${distDir} — run "npm run build" first.`);
  process.exit(1);
}

console.log(`[deploy] clearing ${wwwroot}`);
await rm(wwwroot, { recursive: true, force: true });
await mkdir(wwwroot, { recursive: true });

console.log(`[deploy] copying ${distDir} -> ${wwwroot}`);
await cp(distDir, wwwroot, { recursive: true });

// Keep the directory tracked in git after the wipe (the built assets themselves are gitignored).
await writeFile(
  resolve(wwwroot, '.gitkeep'),
  '# Build output dir — keep tracked; the SPA assets here are gitignored and regenerated by `npm run deploy`.\n',
);

console.log('[deploy] done. The .NET host now serves the built dashboard from wwwroot.');
