// Builds the web app and copies apps/web/dist into the .NET host's wwwroot for single-host serving.
// Idempotent: wwwroot is wiped and repopulated each run so stale hashed assets don't accumulate.
import { spawnSync } from 'node:child_process';
import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const workspace = fileURLToPath(new URL('../', import.meta.url));
const source = new URL('../apps/web/dist/', import.meta.url);
const wwwroot = new URL('../../wheelhouse.backend-services/Wheelhouse.Api/wwwroot/', import.meta.url);

const build = spawnSync('pnpm', ['--filter', '@wheelhouse/web', 'build'], { cwd: workspace, stdio: 'inherit' });
if (build.error) throw build.error;
if (build.status !== 0) process.exit(build.status ?? 1);

await rm(wwwroot, { recursive: true, force: true });
await mkdir(wwwroot, { recursive: true });
await cp(source, wwwroot, { recursive: true });

// Keep the directory tracked in git after the wipe (the built assets themselves are gitignored).
await writeFile(
  new URL('.gitkeep', wwwroot),
  '# Build output dir — keep tracked; the SPA assets here are gitignored and regenerated by `pnpm run deploy`.\n',
);

console.log('[deploy] Copied apps/web/dist to Wheelhouse.Api/wwwroot.');
